### ISSUE TITLE
Process-plugin creates zombie processes

### ISSUE THREAD

**Issue by jari-omniata** [hayajo/Mojolicious-Plugin-Process#3]
The plugin works very well to the point the newly fork()ed child process has run its course and is about to exit. As the classic IPC-model in *nixes goes: the child process will turn into a zombie until calling parent will call wait().

That's exactly what happenes here. Plugin-code doesn't have the wait()-call anywhere.

The fix is to add a simple:
```
waitpid($pid, WNOHANG);
```
Where $pid is the PID returned by a $self->process() call. It is not necessary to write code to handle the CHLD-signal, Perl does that.  Mojolicious doesn't touch the signal handler and when queried for current value, it returns DEFAULT.

Example run:
```
for round in {1..500}; do curl http://localhost:8888/; done
```
Compare the results, asking for number of zombie processes found:
```
ps ax | fgrep defunct | wc -l
```
Without waitpid()-call, result will be 501 (one for the fgrep). With waitpid()-call, result will be 1.

**Comment by hayajo** [comment]
Hi, @jari-omniata.

I fixed creates zombie processes in dev branch. What do you think?

https://github.com/hayajo/Mojolicious-Plugin-Process/commit/15b6fe1820f890ddbab691d8bbc3edc6b10cd347

**Comment by hayajo** [comment]
https://github.com/hayajo/Mojolicious-Plugin-Process/commit/15b6fe1820f890ddbab691d8bbc3edc6b10cd347 merged on master.

https://github.com/hayajo/Mojolicious-Plugin-Process/commit/343558e883ec1c95b2ed336d365fa2d2b5144032
